pool: "Default"


trigger:
  branches:
    include:
      - main
  paths:
    include:
      - .azure/*
      - docker/litellm/*
pr:
  branches:
    include:
      - '*'

variables:
  - group: kw-nexus-reader
  - name: image_name
    value: R2R litellm
  - name: main_repository_name
    value: 'drupalwiki_r2r_litellm'
  - name: dockerfile_image_basepath_relative
    value: 'docker/litellm'

resources:
  repositories:
    - repository: dockerfile_library
      type: github
      name: KontextWork/dockerfile_library
      ref: master
      endpoint: KontextWork
    - repository: azureCommonTemplates
      type: github
      name: KontextWork/azure-common-templates
      ref: master
      endpoint: KontextWork
jobs:
  - job: docker_image
    displayName: Building docker image ${{ variables.image_name }}
    dependsOn: []
    steps:
    - checkout: self
      fetchDepth: 5
    - checkout: dockerfile_library
      fetchDepth: 1
    - template: action/git/find_best_branch_name.yml@azureCommonTemplates
    - template: action/docker/build-image.yml@azureCommonTemplates
      parameters:
        main_repository_name: $(main_repository_name)
        dockerfile_basepath_relative:  $(dockerfile_image_basepath_relative)
        docker_image_name: 'rag/r2r/litellm'
        dockerfile_filename: 'Dockerfile'
        docker_image_tag: "build-nr-$(Build.BuildNumber)"
        docker_image_tags_extra: "build-latest build-latest-$(best_branch_name)"
        cache_base_tag: "build-latest-$(best_branch_name)"
        vsc_commit_hash: $(Build.SourceVersion)
        vsc_branch: $(best_branch_name_long)
        ci_build_number: $(Build.BuildNumber)

